In [2]:
import pandas as pd

In [4]:
# pandas series
d=[1,2,3,4]
s=pd.Series(d)
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [7]:
# custom index
d=[1,2,3,4]
i=['a','s','d','f']
series=pd.Series(d,index=i)
print(series)

a    1
s    2
d    3
f    4
dtype: int64


In [8]:
#dictionary
d={'a':1,'b':2,'c':3}
s=pd.Series(d)
print(s)

a    1
b    2
c    3
dtype: int64


In [9]:
series.replace(2,5)

a    1
s    5
d    3
f    4
dtype: int64

In [12]:
import numpy as np
d=np.array([10,20,30])
s=pd.Series(d,index=['a','b','c'])
print(s)

a    10
b    20
c    30
dtype: int32


In [13]:
s={'nmae':['alice','bab','cat'],'age':[23,43,55] , \
   'country':['us','india','uk']}
d=pd.DataFrame(s)
print(d)


    nmae  age country
0  alice   23      us
1    bab   43   india
2    cat   55      uk


In [17]:
import numpy as np
a=np.array([[1,2,3],[5,6,7],[8,9,0]])
print(a)
df=pd.DataFrame(a,columns=['a','b','c'])
print(df)

[[1 2 3]
 [5 6 7]
 [8 9 0]]
   a  b  c
0  1  2  3
1  5  6  7
2  8  9  0


In [18]:
import numpy as np
a=np.array([[1,2,3],[5,6,7],[8,9,0]])
print(a)
df=pd.DataFrame(a)
print(df)

[[1 2 3]
 [5 6 7]
 [8 9 0]]
   0  1  2
0  1  2  3
1  5  6  7
2  8  9  0
